name: first-action
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'Anonymous'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Greet Person
        with:
          name: ${{ github.event.inputs.name || 'World' }}
        run: echo "Hello, ${{ github.event.inputs.name || 'World' }}!"
