name: List services in GCP
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  show-oidc:
    runs-on: ubuntu-latest
    steps:
    - name: Request OIDC Token
      id: get_token
      run: |
        curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL" > oidc.json
        cat oidc.json
        echo "OIDC_TOKEN=$(jq -r '.value' < oidc.json)" >> $GITHUB_ENV
    
    - name: Decode OIDC Token
      run: |
        echo "$OIDC_TOKEN" | cut -d '.' -f2 | base64 -d | jq
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: "compute-0fa3ddfe"
          workload_identity_provider: 'projects/307894880056/locations/global/workloadIdentityPools/oidc-pool/providers/github-actions'
          service_account: 'gihub-service-account@compute-0fa3ddfe.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: "compute-0fa3ddfe"

      - name: 'Use gcloud CLI'
        run: 'gcloud auth list --filter=status:ACTIVE --format="value(account)"'

      # - name: 'List buckets in project'
      #   run: |
      #     # gcloud auth list
      #     gsutil ls -p compute-0fa3ddfe
