name: opa-bundle-ci
on:
    push:
        branches:
            - main
        paths:
            - '.github/workflows/opa-bundle.yaml'
            - 'opa/**'
    pull_request:
        branches:
            - main
        paths:
            - '.github/workflows/opa-bundle.yaml'
            - 'opa/**'
    workflow_dispatch:
jobs:
    opa-bundle:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                sparse-checkout: |
                  .github
                  opa

            - name: Set up OPA
              uses: open-policy-agent/setup-opa@v2
              with:
                  version: 0.67.1

            - name: Run OPA Test
              run: |
                  opa test ./opa/terraform/ --verbose 

            - name: Build opa bundle
              run: |
                  opa build ./opa/terraform/ 
            
            - name: Upload OPA Bundle
              uses: actions/upload-artifact@v4
              with:
                name: opa-bundle
                path: |
                  bundle.tar.gz
    
    opa-apply:
        runs-on: ubuntu-latest
        needs: opa-bundle
        steps:
          - name: Download OPA Bundle
            uses: actions/download-artifact@v4
            with:
                name: opa-bundle
          - name: List files
            run: |
                ls -la