name: opa-bundle-ci
on:
    push:
        branches:
            - main
        paths:
            - '.github/workflows/opa-bundle.yaml'
            - 'opa/**'
    pull_request:
        branches:
            - main
        paths:
            - '.github/workflows/opa-bundle.yaml'
            - 'opa/**'
    workflow_dispatch:
jobs:
    opa-bundle:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                sparse-checkout: |
                  .github
                  opa

            - name: Set up OPA
              uses: open-policy-agent/setup-opa@v2
              with:
                  version: 0.67.1

            - name: Run OPA Test
              run: |
                  opa test ./opa/terraform/ --verbose 

            # - name: Run OPA Bundle
            #   run: |
            #       opa run --bundle ./bundle.tar.gz --server --set=decision_logs.console=true