name: reusable-workflow-test
on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Number to find factorial of'
        required: true
        type: number
jobs:
    JobA:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Find Factorial
          uses: ./.github/workflows/find_factorial.yaml
          with:
            number: ${{ github.event.inputs.number }}