name: reusable-workflow-test
on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Number to find factorial of'
        required: true
        type: number
jobs:
    find_factorial:
        uses: ./.github/workflows/find_factorial.yaml
        with:
          number: ${{ github.event.inputs.number }}